KOD-5.2
Ramdez1980/kodilla-basic-tests pull request #9
Opened 2021-08-29 14:52 UTC by Ramdez1980

2021-08-29 15:01 UTC, mps4dev requested changes

2021-08-29 15:01 UTC, mps4dev commented on kodilla-collections-advanced/src/main/java/adv/maps/homework/SchoolDirectory.java
> +            System.out.println(schoolEntryEntry.getKey().getSchoolName()
tak nie robimy z tym sout, bo jest nieczytelny zapis. Prosze napisac metode prywatna private String describeSchool(Principal principal, School school), ktora zwroci stringa ktorego masz w liniach 23-30.
Do tego klamerki dla petli for poprosze.

2021-08-29 15:27 UTC, Ramdez1980 commented on kodilla-collections-advanced/src/main/java/adv/maps/homework/School.java
> +    private List<Integer> school = new ArrayList<>();
Tak było w poleceniu "Klasę School, która będzie reprezentowała szkołę, a w niej pole (typu ArrayList), które będzie przechowywało listę liczb uczniów w poszczególnych klasach."

2021-09-01 20:52 UTC, mps4dev approved these changes

2021-09-02 07:08 UTC, merged